/* Generated By:JavaCC: Do not edit this line. SimpLengConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpLengConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PR_Pkg = 5;
  /** RegularExpression Id. */
  int PR_Mn = 6;
  /** RegularExpression Id. */
  int PR_imp = 7;
  /** RegularExpression Id. */
  int PR_DV = 8;
  /** RegularExpression Id. */
  int PR_fmt = 9;
  /** RegularExpression Id. */
  int PR_Scan = 10;
  /** RegularExpression Id. */
  int PR_print = 11;
  /** RegularExpression Id. */
  int PR_If = 12;
  /** RegularExpression Id. */
  int PR_Else = 13;
  /** RegularExpression Id. */
  int PR_For = 14;
  /** RegularExpression Id. */
  int PR_Return = 15;
  /** RegularExpression Id. */
  int PR_Funcion = 16;
  /** RegularExpression Id. */
  int D_ParentI = 17;
  /** RegularExpression Id. */
  int D_ParentD = 18;
  /** RegularExpression Id. */
  int D_CorchI = 19;
  /** RegularExpression Id. */
  int D_CorchD = 20;
  /** RegularExpression Id. */
  int D_LlaveI = 21;
  /** RegularExpression Id. */
  int D_LlaveD = 22;
  /** RegularExpression Id. */
  int D_Coma = 23;
  /** RegularExpression Id. */
  int OC_Mas = 24;
  /** RegularExpression Id. */
  int OC_Menos = 25;
  /** RegularExpression Id. */
  int OC_Por = 26;
  /** RegularExpression Id. */
  int OC_Entre = 27;
  /** RegularExpression Id. */
  int OC_Menor = 28;
  /** RegularExpression Id. */
  int OC_Mayor = 29;
  /** RegularExpression Id. */
  int OC_MenorI = 30;
  /** RegularExpression Id. */
  int OC_MayorI = 31;
  /** RegularExpression Id. */
  int OC_Asignar = 32;
  /** RegularExpression Id. */
  int OC_Diferente = 33;
  /** RegularExpression Id. */
  int OC_Punto = 34;
  /** RegularExpression Id. */
  int OC_Comilla = 35;
  /** RegularExpression Id. */
  int OC_DComilla = 36;
  /** RegularExpression Id. */
  int OC_Igual = 37;
  /** RegularExpression Id. */
  int OC_Increm = 38;
  /** RegularExpression Id. */
  int OC_Decrem = 39;
  /** RegularExpression Id. */
  int OC_PuntCom = 40;
  /** RegularExpression Id. */
  int OC_Espace = 41;
  /** RegularExpression Id. */
  int PR_true = 42;
  /** RegularExpression Id. */
  int PR_false = 43;
  /** RegularExpression Id. */
  int T_Int = 44;
  /** RegularExpression Id. */
  int T_Float = 45;
  /** RegularExpression Id. */
  int T_String = 46;
  /** RegularExpression Id. */
  int T_Bool = 47;
  /** RegularExpression Id. */
  int S_admiI = 48;
  /** RegularExpression Id. */
  int S_admiD = 49;
  /** RegularExpression Id. */
  int S_gato = 50;
  /** RegularExpression Id. */
  int S_pesos = 51;
  /** RegularExpression Id. */
  int S_and = 52;
  /** RegularExpression Id. */
  int S_interrogaI = 53;
  /** RegularExpression Id. */
  int S_interrogaD = 54;
  /** RegularExpression Id. */
  int LetraMin = 55;
  /** RegularExpression Id. */
  int LetraMay = 56;
  /** RegularExpression Id. */
  int Numero = 57;
  /** RegularExpression Id. */
  int Number = 58;
  /** RegularExpression Id. */
  int Constante = 59;
  /** RegularExpression Id. */
  int Variable = 60;
  /** RegularExpression Id. */
  int String = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"package\"",
    "\"main\"",
    "\"import\"",
    "\"var\"",
    "\"fmt\"",
    "\"Scan\"",
    "\"Println\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"return\"",
    "\"func\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\".\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"==\"",
    "\"++\"",
    "\"--\"",
    "\";\"",
    "\"_\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"float64\"",
    "\"string\"",
    "\"bool\"",
    "\"\\u00c2\\u00a1\"",
    "\"!\"",
    "\"#\"",
    "\"$\"",
    "\"&\"",
    "\"\\u00c2\\u00bf\"",
    "\"?\"",
    "<LetraMin>",
    "<LetraMay>",
    "<Numero>",
    "<Number>",
    "<Constante>",
    "<Variable>",
    "<String>",
  };

}
